version: '3'
services:
  backend:
    image: rayfield24/dental_avenue_node
    build: .
    command: "yarn start"
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
